# Generated by Django 5.2.1 on 2025-05-30 15:12

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("almacen", "0002_almacenvaloracion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Objeto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(max_length=500)),
                (
                    "imagen",
                    models.ImageField(blank=True, null=True, upload_to="imagenes/"),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Bricolaje", "Bricolaje"),
                            ("Jardín", "Jardín"),
                            ("Cocina", "Cocina"),
                            ("Electrónica", "Electrónica"),
                            ("Herramientas", "Herramientas"),
                            ("Limpieza", "Limpieza"),
                            ("Otros", "Otros"),
                        ]
                    ),
                ),
                (
                    "condicion",
                    models.CharField(
                        choices=[
                            ("Nuevo", "Nuevo"),
                            ("Bueno", "Bueno"),
                            ("Desgastado", "Desgastado"),
                            ("Perdido", "Perdido"),
                        ]
                    ),
                ),
                ("huella_carbono", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "almacen",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="objetos",
                        to="almacen.almacen",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ObjetoValoracion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "estrellas",
                    models.PositiveIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comentario", models.TextField(blank=True, null=True)),
                (
                    "objeto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_recibidas_objeto",
                        to="objeto.objeto",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valoraciones_impuestas_objeto",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("objeto", "usuario")},
            },
        ),
    ]
