# Generated by Django 5.2.1 on 2025-05-30 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("objeto", "0002_objetovaloraciondenuncia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="objeto",
            options={"verbose_name": "Objeto", "verbose_name_plural": "Objetos"},
        ),
        migrations.AlterModelOptions(
            name="objetovaloracion",
            options={
                "verbose_name": "Valoración de Objeto",
                "verbose_name_plural": "Valoraciones de Objetos",
            },
        ),
        migrations.AlterModelOptions(
            name="objetovaloraciondenuncia",
            options={
                "verbose_name": "Denuncia de Valoración de Objeto",
                "verbose_name_plural": "Denuncias de Valoraciones de Objetos",
            },
        ),
    ]
