# Generated by Django 5.2.1 on 2025-06-11 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0003_alter_objeto_options_alter_objetovaloracion_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='objeto',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='objetos_deseados', to=settings.AUTH_USER_MODEL),
        ),
    ]
