# Generated by Django 5.2.1 on 2025-07-01 16:45

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0004_objeto_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='imagen'),
        ),
    ]
