# Generated by Django 5.2.1 on 2025-07-02 16:36

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('objeto', '0005_alter_objeto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='objeto',
            name='imagen',
            field=cloudinary.models.CloudinaryField(default='https://res.cloudinary.com/cosateca/image/upload/v1751389089/placeholder_oiztci.png', max_length=255, verbose_name='imagen'),
        ),
    ]
