# Generated by Django 5.2.1 on 2025-05-30 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0002_almacenvaloracion"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ObjetoValoracionDenuncia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(
                        choices=[
                            ("Opinión falsa", "Opinión falsa"),
                            ("Lenguaje ofensivo", "Lenguaje ofensivo"),
                            ("Acoso", "Acoso"),
                            ("Contenido sexual", "Contenido sexual"),
                            ("Autolesiones", "Autolesiones"),
                            ("Difamación", "Difamación"),
                            ("Violación de privacidad", "Violación de privacidad"),
                            ("Otra", "Otra"),
                        ]
                    ),
                ),
                ("fecha_creacion", models.DateTimeField(auto_now_add=True)),
                ("contexto", models.TextField(max_length=500)),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias_impuestas_valoracion_almacen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valoracion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="denuncias_recibidas_almacen",
                        to="almacen.almacenvaloracion",
                    ),
                ),
            ],
            options={
                "unique_together": {("valoracion", "usuario")},
            },
        ),
    ]
