# Generated by Django 5.2.1 on 2025-05-30 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0003_objetovaloraciondenuncia"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="almacen",
            options={"verbose_name": "Almacén", "verbose_name_plural": "Almacenes"},
        ),
        migrations.AlterModelOptions(
            name="almacenvaloracion",
            options={
                "verbose_name": "Valoración de Almacén",
                "verbose_name_plural": "Valoraciones de Almacenes",
            },
        ),
        migrations.AlterModelOptions(
            name="horario",
            options={
                "verbose_name": "Horario de Almacén",
                "verbose_name_plural": "Horarios de Almacenes",
            },
        ),
        migrations.AlterModelOptions(
            name="localizacion",
            options={
                "verbose_name": "Localización",
                "verbose_name_plural": "Localizaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="objetovaloraciondenuncia",
            options={
                "verbose_name": "Denuncia de Valoración de Almacén",
                "verbose_name_plural": "Denuncias de Valoraciones de Almacenes",
            },
        ),
    ]
