# Generated by Django 5.2.1 on 2025-07-14 16:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("almacen", "0004_alter_almacen_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ObjetoValoracionDenuncia",
            new_name="AlmacenValoracionDenuncia",
        ),
    ]
