# Generated by Django 5.2.1 on 2025-05-27 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Preferencia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tarea_tipo", models.CharField()),
                ("frecuencia_uso", models.CharField()),
                ("experiencia", models.CharField()),
                ("franja_horaria", models.CharField()),
                (
                    "usuario",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="preferencia",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
