# Generated by Django 5.2.1 on 2025-05-29 18:12

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '__first__'),
        ('usuario', '0002_preferencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preferencia',
            name='experiencia',
            field=models.CharField(choices=[('Principiante', 'Principiante'), ('Intermedio', 'Intermedio'), ('Avanzado', 'Avanzado')]),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='franja_horaria',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde'), ('Fines de semana', 'Fines de semana'), ('Sin preferencia', 'Sin preferencia')]),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='frecuencia_uso',
            field=models.CharField(choices=[('Diario', 'Diario'), ('Semanal', 'Semanal'), ('Mensual', 'Mensual'), ('Ocasiones puntuales', 'Ocasiones puntuales')]),
        ),
        migrations.AlterField(
            model_name='preferencia',
            name='tarea_tipo',
            field=models.CharField(choices=[('Bricolaje', 'Bricolaje'), ('Jardín', 'Jardín'), ('Cocina', 'Cocina'), ('Electrónica', 'Electrónica'), ('Herramientas', 'Herramientas'), ('Limpieza', 'Limpieza'), ('Otros', 'Otros')]),
        ),
        migrations.CreateModel(
            name='Gestor',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('almacen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gestores', to='almacen.almacen')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('usuario.usuario',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Amonestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField(max_length=500)),
                ('severidad', models.CharField(choices=[('Leve', 'Leve'), ('Media', 'Media'), ('Grave', 'Grave')])),
                ('fecha', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones_recibidas', to=settings.AUTH_USER_MODEL)),
                ('gestor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='amonestaciones_creadas', to='usuario.gestor')),
            ],
        ),
    ]
