# Generated by Django 5.2.1 on 2025-05-30 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("usuario", "0003_alter_preferencia_experiencia_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="amonestacion",
            options={
                "verbose_name": "Amonestación",
                "verbose_name_plural": "Amonestaciones",
            },
        ),
        migrations.AlterModelOptions(
            name="gestor",
            options={"verbose_name": "Gestor", "verbose_name_plural": "Gestores"},
        ),
        migrations.AlterModelOptions(
            name="preferencia",
            options={
                "verbose_name": "Preferencia",
                "verbose_name_plural": "Preferencias",
            },
        ),
        migrations.AlterModelOptions(
            name="usuario",
            options={"verbose_name": "Usuario", "verbose_name_plural": "Usuarios"},
        ),
    ]
